#!/usr/bin/env bash
# shellcheck shell=bash
# - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202605191156-git
# @@Author           :  Jason Hempstead
# @@Contact          :  git-admin@casjaysdev.pro
# @@License          :  MIT or LICENSE.md
# @@ReadME           :  timezone-setup --help | README.md
# @@Copyright        :  Copyright: (c) 2026 Jason Hempstead, Casjays Developments
# @@Created          :  Tuesday, May 19, 2026 11:56 EDT
# @@File             :  timezone-setup
# @@Description      :  Set system timezone using timedatectl with /etc/localtime fallback
# @@Changelog        :  Add compliant script header; fix convention violations
# @@TODO             :
# @@Other            :
# @@Resource         :
# @@Terminal App     :  yes
# @@sudo/root        :  yes
# @@Template         :  shell/bash
# - - - - - - - - - - - - - - - - - - - - - - - - -
# shellcheck disable=SC1001,SC1003,SC2001,SC2003,SC2016,SC2031,SC2090,SC2115,SC2120,SC2155,SC2199,SC2229,SC2317,SC2329
# - - - - - - - - - - - - - - - - - - - - - - - - -
VERSION="202605191156-git"
APPNAME="${0##*/}"
RUN_USER="${USER}"
SET_UID="${UID}"
SCRIPT_SRC_DIR="${BASH_SOURCE%/*}"
# - - - - - - - - - - - - - - - - - - - - - - - - -
set -eu

case "${1:-}" in
    --version|-V) printf "%s v%s\n" "$(basename "$0")" "${VERSION}"; exit 0 ;;
    --help|-h)
        printf "Usage: timezone-setup <timezone>\n\n"
        printf "Example: timezone-setup America/New_York\n"
        printf "List zones: timedatectl list-timezones\n"
        exit 0 ;;
esac

TZ="${1:?Usage: timezone-setup <timezone>  e.g. America/New_York}"

if [ ! -f "/usr/share/zoneinfo/${TZ}" ]; then
    echo "Unknown timezone: ${TZ}" >&2
    echo "Run 'timedatectl list-timezones' for valid names." >&2
    exit 1
fi

timedatectl set-timezone "${TZ}" 2>/dev/null \
    || ln -sf "/usr/share/zoneinfo/${TZ}" /etc/localtime
echo "Timezone set to ${TZ}"
# ex: ts=2 sw=2 et filetype=sh
